# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

spark.sql("USE CATALOG `workspace`")
spark.sql("USE SCHEMA `bookstore_etl_pro`")

# COMMAND ----------

dataset_path = spark.conf.get("dataset_path")

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from workspace.bookstore_etl_pro.bronze

# COMMAND ----------

# MAGIC %sql 
# MAGIC select cast(unbase64(value) as string) from workspace.bookstore_etl_pro.bronze
# MAGIC where topic='customers'
